# fly.toml app configuration file
app = "chrono-code"
primary_region = "eze"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start = true
  min_machines_running = 1

[env]
  PORT = "8000"

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[resources]
  memory = 1024
  cores = 1
